---
title: "Aggregate data per segment"
author: "Martijn Koole"
date: "12/23/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache=T)
```

## Test
First test with only the years in which the first damage is observed
```{r aggregate}
load("data/r_int_tot.RData")

r.first.damage<- r.int.tot[r.int.tot$eerste.schade == 1,]

source("prepare.R")
r.first.damage<- prepare(r.first.damage)


xnam <- colnames(r.first.damage)
xnam<- xnam[! xnam %in% c("verloop","WEG","BAAN","VAN","TOT","AANLEGDATUM","INTERVENTIEJAAR_RAF","jr.tot.interventie","afst.obst",
                          "BUITENSTE_RIJSTROOK","jaar","WEG.BAAN.STROOK.VAN","vervangen","vervangen.leeftijd","WEG.BAAN.STROOK.VAN.JAAR","eerste.schade",
                          "verdacht","vvr","ldr.verw","WEG.VAN.BAAN","x","y", "WVK_ID","district", "dienst","schade","WEG.VAN.BAAN.JAAR",
                          "MPD_midden2015","MPD_rechts2015","MPD_links2015","deklaagsoort.lag","vervangen.leeftijd",
                          "asdruk1_mean","asdruk1_P_50","asdruk1_P_84","asdruk2_mean","asdruk2_P_50","asdruk2_P_84",
                          "eerste.schade","eerste.schade.leeftijd","verschil_planjaar","verloop",
                          "aanleg.FG","aanleg.FHX","aanleg.TG","aanleg.TX","aanleg.TN","stroefheid2015",
                          "langsonvlakheid2015","dwarsonvlakheid2015")]
fmla <- as.formula(paste("schade ~ ", paste(xnam, collapse= "+")))



library(rpart)
library(rpart.plot)
library(caret)

train<- r.first.damage[r.first.damage$jaar != 2013,]
test<- r.first.damage[r.first.damage$jaar == 2014,]

```
Decision tree

```{r tree}
tree<- rpart(fmla,train,method = "class",)
#png("plots/tree_2012.png",width = 1000,height = 1000,res=100)
rpart.plot(tree,cex=0.7,yesno=T,type=2,compress=T)
#dev.off()
#summary(tree)
#library(rattle)
#fancyRpartPlot(tree_2014,cex=0.5) 

test$pred_tree<- predict(tree,test,typ="class")

confusionMatrix(test$schade,test$pred_tree)
```



Random forest
```{r rf}
####RF
library(randomForest)

#train$schade<- ifelse(train$schade == 1, "schade",ifelse(train$schade == 0, "geen schade",NA))
#train$schade<- as.factor(train$schade)

#na_count <-sapply(train, function(y) sum(is.na(y)))

#na_count/nrow(train)

train$schade<- as.factor(train$schade)

rf<- randomForest(fmla,data=train,ntree=100,importance=T,na.action = na.omit)


test$rf_res<- predict(rf,test)

confusionMatrix(test$schade,test$rf_res)

plot(rf)
varImpPlot(rf)
summary(rf)


```


## Aggregation

This script aggregates the r.int.tot data to rows that represent the lifetime of a segment until damage occurs. In this way, the age at which damage occurs could be learned using ML.
